### PR TITLE
Fix typings to accomodate spread flag

### LINKED ISSUE #69: Typescript typings are not correct
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: any
* *module version with issue*: >= 4.1.2
* *last module version without issue*: < 4.1.2
* *environment* (e.g. node, browser, native): any
* *used with* (e.g. hapi application, another framework, standalone, ...): anything
* *any other relevant information*: no

#### What are you trying to achieve or the steps to reproduce?
Use official typings

I believe the typescript typings provided in the last version are just wrong.

If you check Podium´s source code:

https://github.com/hapijs/podium/blob/5b81f6f4cd98d7271f4c2ae655b7776d87c24a08/lib/index.js#L211-L230

You can see that, if the `spread` flag is passed when creating the event, Podium will spread the event arguments over the callback function when invoking it. However, the new typings listener doesn't account for that:

https://github.com/hapijs/podium/blob/5b81f6f4cd98d7271f4c2ae655b7776d87c24a08/lib/index.d.ts#L197-L198

Considering how the current hapi typings is written, I can´t see why any changes would be necessary, the new typings are just wrong, unless I´m missing something.

Link to the API: https://hapi.dev/module/podium/api/?v=4.1.1#spread

This is a copy from the bug request opened in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52135#issuecomment-812237555

#### What was the result you got?
Non-working typings

#### What result did you expect?
Working typings

### PR DESCRIPTION
**Pull request by saboya**
This fixes #69

### CODE REVIEW

**Review by kanongil — APPROVED** [review]
I revised the PR, tightening it up a bit with additional tests.

This makes the default type for an event callback `unknown[]`, which means that any non-casted usage will trigger a type-error. A user can then fix this by specifying the types in the `on/once` generic argument, or by adding the types to the callback function arguments.

The `= any[]` declarations are needed to support overriding the type for specific events in a subclass declaration, like `@types/hapi__hapi` cleverly does.

**Comment by kanongil** [comment]
FYI, with this patch the hapi typings can be fixed to work with the new types.

**Comment by saboya** [comment]
@kanongil Yeah, with these new typings I believe it´s possible.

I have a more drastic suggestion (WIP) to allow better typing for events, which may or may not be desired, but I´ll leave that for another PR.

Thanks for the quick review.

**Comment by saboya** [comment]
Any chance to get this merged?

**Pull request merged**
